# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Hydration-Tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hydration-Tracker
   pod 'Parse'
   pod 'AlamofireImage'

  target 'Hydration-TrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hydration-TrackerUITests' do
    # Pods for testing
  end

end
